const express = require('express')
const api = express.Router()
const multipart = require('connect-multiparty')
const SongController = require('../controllers/song')
const md_files = multipart({uploadDir: './uploads/songs'})
const middlewares =  require('../middlewares/check-auth')

api.get('/:id?', middlewares.verify_auth ,SongController.get_songs)
api.post('/', middlewares.verify_auth ,SongController.save_song)
api.get('/:id/details', middlewares.verify_auth ,SongController.get_song)
api.put('/:id', middlewares.verify_auth ,SongController.update_song)
api.delete('/:id', middlewares.verify_auth ,SongController.remove_song)
api.post('/add-file/:id', [middlewares.verify_auth, md_files] ,SongController.add_file)
api.get('/get-file/:filename', middlewares.verify_auth ,SongController.get_file)
module.exports = api